language: python

python:
  - '3.8.1'

before_install:
  - python -m pip install --upgrade pip
  
install:
  - pip install -r requirements.txt

services:
  - postgresql

before_script:


  - psql -c 'create database sitevoyance;' -U postgres

env:
  - DJANGO_SETTINGS_MODULE=magicballconfig.settings.travis

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test