language: python

python:
  - '3.8.1'

before_install:
  - python -m pip install --upgrade pip
  
install:
  - pip install -r requirements.txt

services:
  - postgresql

before_script:
  - wget https://chromedriver.storage.googleapis.com/83.0.4103.14/chromedriver_linux64.zip

  - unzip chromedriver_linux64.zip -d /home/travis/build/NunoMars/lastProject/

  - export CHROME_BIN=chromium-browser

  - psql -c 'create database sitevoyance;' -U postgres

env:
  - DJANGO_SETTINGS_MODULE=siteVoyanceconfig.settings.travis

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test